# Generated by Django 3.2.5 on 2021-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('sekolah_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('siap_id', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('npsn', models.CharField(max_length=255)),
                ('is_negri', models.BooleanField(default=True)),
                ('is_sbi', models.BooleanField(default=False)),
                ('k_kota', models.CharField(max_length=255)),
                ('k_propinsi', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=255)),
                ('propinsi', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
            ],
        ),
    ]
