# Generated by Django 3.2.5 on 2021-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nilai', models.JSONField()),
                ('siswa_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jalur', models.CharField(max_length=255)),
                ('nilai_total', models.CharField(max_length=10)),
                ('acc', models.CharField(max_length=255)),
                ('pilihan1', models.CharField(max_length=255)),
                ('pilihan2', models.CharField(max_length=255, null=True)),
                ('pilihan3', models.CharField(max_length=255, null=True)),
                ('pilihanPenjurusan', models.JSONField(default=dict)),
                ('year', models.CharField(max_length=5)),
                ('zonasi', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
