# Generated by Django 3.2.5 on 2021-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_siswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='zonasi',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
