# Generated by Django 3.2.5 on 2021-08-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_siswa_zonasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ringkasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rata2', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('year', models.CharField(max_length=5)),
                ('sum_type', models.CharField(default='all', max_length=50)),
                ('sekolah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sekolah')),
            ],
        ),
    ]
