# Generated by Django 3.2.5 on 2021-08-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ringkasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkasan',
            name='sekolah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sekolah'),
        ),
    ]
