# Generated by Django 3.2.5 on 2021-08-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ringkasan_sekolah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ringkasan',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ringkasan',
            name='rata2',
            field=models.FloatField(),
        ),
    ]
