# Generated by Django 3.2.5 on 2021-08-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210803_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediksi', models.FloatField()),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sekolah')),
            ],
        ),
    ]
